SELECT nome FROM tabela_de_clientes, notas_fiscais WHERE VOLUME_DE_COMPRA >2000 AND data_venda LIKE "%2016%"

  SELECT CPF, COUNT(*) FROM notas_fiscais
  WHERE YEAR(DATA_VENDA) = 2016
  GROUP BY CPF
  HAVING COUNT(*) > 2000
  
  select CPF, SUM(VOLUME_DE_COMPRA) from 
  notas_fiscais WHERE DATA_VENDA LIKE "%2016%" GROUP BY CPF HAVING SUM(VOLUME_DE_COMPRA)>2000
  
  select * from notas_fiscais
  
  select volume_de_compra from tabela_de_clientes
  
  select CPF, COUNT(*) from notas_fiscais
  WHERE DATA_VENDA LIKE '%2016%' 
  GROUP BY CPF 
  HAVING COUNT(*)>2000
  
SELECT NOME, IDADE,
CASE WHEN IDADE > 20 THEN 'VELHO'
    ELSE 'NOVO'
    END AS "VelhoNovo"
FROM tabela_de_clientes
    
    
    
SELECT NOME,
CASE WHEN YEAR(data_de_nascimento) < 1990 THEN 'Velho'
WHEN YEAR(data_de_nascimento) >= 1990 AND
YEAR(data_de_nascimento) <= 1995 THEN 'Jovens' 
ELSE 'Crianças' 
END  AS "CLASSIFICAÇÃO POR IDADE"
FROM tabela_de_clientes;



SELECT YEAR(DATA_VENDA), SUM(QUANTIDADE * PRECO) AS FATURAMENTO
FROM notas_fiscais NF INNER JOIN itens_notas_fiscais INF 
ON NF.NUMERO = INF.NUMERO
GROUP BY YEAR(DATA_VENDA);

SELECT NOME_DO_PRODUTO, EMBALAGEM, TAMANHO, SABOR FROM tabela_de_produtos  WHERE SABOR = 'Laranja'

SELECT NOME FROM tabela_de_clientes WHERE NOME LIKE '%Carvalho%'

SELECT DISTINCT SABOR FROM tabela_de_produtos

SELECT DISTINCT SABOR FROM tabela_de_produtos LIMIT 1,4

SELECT COUNT(*) FROM tabela_de_clientes WHERE NOME LIKE '%Mattos%'

SELECT DISTINCT BAIRRO FROM tabela_de_clientes WHERE CIDADE = 'Rio de Janeiro'

SELECT * FROM notas_fiscais WHERE DATA_VENDA = '2017-01-01' LIMIT 10

select * from notas_fiscais

SELECT * from tabela_de_clientes WHERE IDADE > 20 HAVING SEXO = 'M' ORDER BY NOME

SELECT COUNT(*), IDADE FROM tabela_de_clientes  GROUP BY IDADE

select COUNT(*), IDADE from

SELECT X.CLASSIFICACAO FROM(
CASE WHEN IDADE < 20 THEN 'NOVO' 
WHEN IDADE >=20 AND IDADE <30 THEN 'JOVEM' 
ELSE 'VELHO' 
END AS 'CLASSIFICACAO' 
FROM tabela_de_clientes) X

SELECT COUNT(*),
CASE WHEN IDADE < 20 THEN 'NOVO' 
WHEN IDADE >=20 AND IDADE <30 THEN 'JOVEM' 
ELSE 'VELHO' 
END AS 'CLASSIFICACAO' 
FROM tabela_de_clientes
GROUP BY CLASSIFICACAO

SELECT NOME, 

SELECT NOME, TIMESTAMPDIFF (YEAR, DATA_DE_NASCIMENTO, CURDATE()) AS    IDADE
FROM  tabela_de_clientes

SELECT NOME, TIMESTAMPDIFF(YEAR, DATA_DE_NASCIMENTO, CURDATE()) AS IDADE
FROM tabela_de_clientes

SELECT YEAR(DATA_VENDA), ROUND(SUM((IMPOSTO * (QUANTIDADE * PRECO))))
FROM notas_fiscais INNER JOIN itens_notas_fiscais ON notas_fiscais.NUMERO = itens_notas_fiscais.NUMERO
WHERE YEAR(DATA_VENDA) = 2016


SELECT CONCAT('O cliente ', TDC.NOME, ' faturou ', SUM(INF.QUANTIDADE * INF.PRECO), ' no ano de 2016')
FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_clientes TDC ON NF.CPF = TDC.CPF
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY NOME;

SELECT CONCAT('O cliente ', TC.NOME, ' faturou ', 
CAST(SUM(INF.QUANTIDADE * INF.preco) AS char (20))
 , ' no ano ', CAST(YEAR(NF.DATA_VENDA) AS char (20))) AS SENTENCA FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_clientes TC ON NF.CPF = TC.CPF
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY TC.NOME, YEAR(DATA_VENDA);

SELECT X.CPF, X.NOME, X.MES_ANO, X.QUANTIDADE_VENDAS, X.QUANTIDADE_LIMITE,
CASE WHEN (X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS) < 0 THEN 'INVÁLIDA'
ELSE 'VÁLIDA' END AS STATUS_VENDA, (1 - (X.QUANTIDADE_LIMITE/X.QUANTIDADE_VENDAS)) * 100 AS PERCENTUAL
FROM (SELECT NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m') AS MES_ANO
, SUM(INF.QUANTIDADE) AS QUANTIDADE_VENDAS 
, MAX(TC.VOLUME_DE_COMPRA) AS QUANTIDADE_LIMITE FROM NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF
ON NF.NUMERO = INF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC 
ON TC.CPF = NF.CPF
GROUP BY NF.CPF, TC.NOME, DATE_FORMAT(NF.DATA_VENDA, '%Y-%m')) X
WHERE (X.QUANTIDADE_LIMITE - X.QUANTIDADE_VENDAS) < 0;

SELECT VENDA_TAMANHO.TAMANHO, VENDA_TAMANHO.ANO, VENDA_TAMANHO.QUANTIDADE,
ROUND((VENDA_TAMANHO.QUANTIDADE/VENDA_TOTAL.QUANTIDADE) * 100, 2) AS PARTICIPACAO FROM 
(SELECT TP.TAMANHO, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM 
TABELA_DE_PRODUTOS TP 
INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY TP.TAMANHO, YEAR(NF.DATA_VENDA)) AS VENDA_TAMANHO
INNER JOIN 
(SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM 
TABELA_DE_PRODUTOS TP 
INNER JOIN ITENS_NOTAS_FISCAIS INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN NOTAS_FISCAIS NF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA) = 2016
GROUP BY YEAR(NF.DATA_VENDA)) AS VENDA_TOTAL
ON VENDA_TAMANHO.ANO = VENDA_TOTAL.ANO
ORDER BY VENDA_TAMANHO.QUANTIDADE DESC